### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by mairastorch** [bwanders/dokuwiki-plugin-stratainline#1]
Hi! I'm very interested in using this syntax. I've searched for instructions but couldn't find any. Are there any examples?

Thanks!

**Comment by mairastorch** [comment]
So I was able to infer how to use two syntaxes from the code: data entry and list. I can't seem to figure out ref entry, which is very, very valuable (specially because of the ability to change the link title).

If this is of anyone's interest...

**Inline data entry**
**[(Predicate[type::hint]*: object1, object2)]** -- as with the regular strata data entry, type, hint and multiple entry indicator (*) are all optional. So the simplest use would be: **[(Predicate: object])**.

**Inline list/query**
I've been able to produce a simple list, with a _very_ simple query. I didn't need to change the separator from a comma, but it's possible, although I didn't take note on how. 

The query syntax is pretty much the same, but instead of having each expression in a new line they are separated by _semicolons_. 

You start by specifying the variables to list, and begin query expressions with a _pipe_ (|).
**{{list>** ?variable-to-list@aggregate [type::hint] **|** expression1 **;** expression2 **}}**

**Comment by bwanders** [comment]
First off, I'm sorry for the belated reply, real life sometimes does that.

**Inline References** What you call the ref is effectively a boosted wiki link. As you know, a normal link is written as `[[Page|Title]]`, this inline reference is written as `[[Predicate~Page|Title]]`. So, to link somewhere one could say `[[Author~user:Brend Wanders]]` to furnish the page with an Author predicate referencing `user:brend_wanders`.

**List syntax** The list syntax is indeed as you note it down, with the addition of the separator: ``{{list> ?var1 ?var2 " sep " | expression1; ... }}`. That is, the separator is set between `"`.

**Display only** The final syntax there is is the 'display only' syntax: `{([type::hint]*: value, value)}`. The only thing it does is use the type and hint for normalisation and display of the given values. This can be useful for types that are neat for their render alone.

**Comment by mairastorch** [comment]
Thank you so much! I completely understand real life getting in the way, just thought to share what I had learned.

On a side note, I'd like to let you know that **inline references** aren't working properly: the value isn't associated to the page and the link created includes the predicate (e.g. id=predicate_ns:page).

**Comment by bwanders** [comment]
> On a side note, I'd like to let you know that **inline references** aren't working properly: the value isn't associated to the page and the link created includes the predicate (e.g. id=predicate_ns:page).

Could you open a new issue for that one with a snippet of wiki syntax snippet that reproduces the problem?
