### ISSUE TITLE
Inline references not working

### ISSUE THREAD

**Issue by mairastorch** [bwanders/dokuwiki-plugin-stratainline#2]
When using the inline reference syntax, no value is associated with the page and the generated link
includes the predicate. Example (text is in portuguese).

```
  * [[Funcionalidade alterada~funcionalidade:Alterar cadastro do cliente]]
  * [[Funcionalidade alterada~funcionalidade:Cadastrar cliente]]
```

Which renders as:
- [Alterar cadastro do cliente](http://...id=funcionalidade_alterada_funcionalidade:alterar_cadastro_do_cliente)
- [Cadastrar cliente](http://...id=funcionalidade_alterada_funcionalidade:cadastrar_cliente)

Links ids: 
- `funcionalidade_alterada_funcionalidade:alterar_cadastro_do_cliente`
- `funcionalidade_alterada_funcionalidade:cadastrar_cliente`

I'm running the latest versions of strata, stratainline and DokuWiki (2014-09-29b "Hrun"), plus several other plugins.

**Comment by bwanders** [comment]
I am not able to reproduce the described behaviour. A clean wiki (running "Hrun"), together with the [strata](/bwanders/dokuwiki-strata) and [stratainline](/bwanders/dokuwiki-stratainline) plugins handles the given example and other tests as expected.

I suspect that the issue occurs due to some interaction with one of the other plugins that also tries to do something with the link syntax. Could you list the plugins you are using so that the issue can be diagnosed, and possibly be clarified with a compatibility warning on the dokuwiki site?

**Comment by mairastorch** [comment]
Sure. There are a lot of them, though (excluding default plugins and strata/stratainline):
- [Add New Page](http://www.dokuwiki.org/plugin:addnewpage)
- [ajaxedit helper plugin](http://dokuwiki.org/plugin:ajaxedit)
- [Bookcreator Plugin](https://www.dokuwiki.org/plugin:bookcreator)
- [Bookmark plugin](https://www.dokuwiki.org/plugin:bookmark)
- [History Cleanup Plugin](http://www.dokuwiki.org/plugin:clearhistory)
- [Comment Syntax support](https://www.dokuwiki.org/plugin:commentsyntax)
- [configuration file manager](http://www.dokuwiki.org/plugin:confmanager)
- [discussion plugin](https://dokuwiki.org/plugin:discussion)
- [Dw2Pdf plugin](https://www.dokuwiki.org/plugin:dw2pdf)
- [edittable plugin](http://www.dokuwiki.org/plugin:edittable)
- [include plugin](http://dokuwiki.org/plugin:include)
- [Indexmenu Plugin](https://www.dokuwiki.org/plugin:indexmenu)
- [linksuggest Plugin](http://www.dokuwiki.org/plugin:linksuggest)
- [newpagetemplate Plugin](http://www.dokuwiki.org/plugin:newpagetemplate)
- [nspages plugin](http://www.dokuwiki.org/plugin:nspages)
- [orphanswanted plugin](http://dokuwiki.org/plugin:orphanswanted)
- [Pagelist Plugin](http://www.dokuwiki.org/plugin:pagelist)
- [Publishing Plugin](http://www.dokuwiki.org/plugin:publish)
- [Site Export](https://www.dokuwiki.org/plugin:siteexport)
- [SwiftMailer Plugin](http://www.dokuwiki.org/plugin:swiftmail)
- [tag plugin](https://www.dokuwiki.org/plugin:tag)
- [tagfilter ](http://dokuwiki.org/plugin:tagfilter)
- [templatepagename plugin](https://dokuwiki.org/plugin:templatepagename)
- [Titles Anchor Link plugin](https://github.com/Dric/Doku-Titles-Anchors)
- [Wrap Plugin](https://www.dokuwiki.org/plugin:wrap)

**Comment by mairastorch** [comment]
I've tried disabling plugins one by one and found the culprit: [Site Export](https://www.dokuwiki.org/plugin:siteexport).

**Comment by bwanders** [comment]
Thanks for putting in the effort to find this out.
